<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Vamsi" failures="2" tests="11" name="Test" time="0.522" errors="0" timestamp="2021-04-03T21:58:54 CDT">
  <testcase classname="testNG.NewTest2" name="f" time="0.039"/>
  <testcase classname="testNG.TestNGDemo1" name="funA" time="0.005"/>
  <testcase classname="testNG.TestNGDemo3" name="funA" time="0.006"/>
  <testcase classname="testNG.TestNGDemo3" name="funD" time="0.005"/>
  <testcase classname="testNG.TestNGDemo3" name="funC" time="0.008"/>
  <testcase classname="testNG.TestNGDemo3" name="funB" time="0.008"/>
  <testcase classname="testNG.TestNGDemo4" name="loginTest" time="0.011">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNG.TestNGDemo4.loginTest(TestNGDemo4.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="testNG.TestNGDemo4" name="customerDetails" time="0.0">
    <skipped/>
  </testcase> <!-- customerDetails -->
  <testcase classname="testNG.TestNGDemo5" name="funA" time="0.007"/>
  <testcase classname="testNG.TestNGDemo5" name="funB" time="0.008">
    <failure type="java.lang.Exception" message="funB failed">
      <![CDATA[java.lang.Exception: funB failed
at testNG.TestNGDemo5.funB(TestNGDemo5.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- funB -->
  <testcase classname="testNG.TestNGDemo5" name="funC" time="0.008">
    <skipped/>
  </testcase> <!-- funC -->
  <testcase classname="testNG.TestNGDemo5" name="funD" time="0.0">
    <ignored/>
  </testcase> <!-- funD -->
</testsuite> <!-- Test -->
